name: "${project.name}"
version: "${project.version}"
api: ["2.0.0"]
main: com.mefrreex.chestcreator.ChestCreator

softdepend:
  - "PlaceholderAPI"
  - "FormCreator"

permissions:
  chestcreator:
    default: true
  chestcreator.open:
    default: op
  chestcreator.info:
    default: true